#!/bin/bash
#python ../cli.py measure --qbank '/home/momentino/PycharmProjects/llm-authority-bias/data/question_bank/neuro/question_bank.csv' --model "claude-3-haiku-20240307" --profession "general neurologist"
#python ../cli.py measure --qbank '/home/momentino/PycharmProjects/llm-authority-bias/data/question_bank/neuro/question_bank.csv' --model "claude-3-haiku-20240307" --profession "general neurologist" --gender "male"

#python ../cli.py measure --qbank '/home/momentino/PycharmProjects/llm-authority-bias/data/question_bank/neuro/question_bank.csv' --model "claude-3-haiku-20240307" --profession "general neurologist" --gender "female"

#python ../cli.py measure --qbank '/home/momentino/PycharmProjects/llm-authority-bias/data/question_bank/neuro/question_bank.csv' --model "claude-3-haiku-20240307" --profession "general neurologist" --gender "male" --position "attending"
#python ../cli.py measure --qbank '/home/momentino/PycharmProjects/llm-authority-bias/data/question_bank/neuro/question_bank.csv' --model "claude-3-haiku-20240307" --profession "general neurologist" --gender "female" --position "attending"

#python ../cli.py measure --qbank '/home/momentino/PycharmProjects/llm-authority-bias/data/question_bank/neuro/question_bank.csv' --model "claude-3-haiku-20240307" --profession "general neurologist" --gender "male" --position "student"
#python ../cli.py measure --qbank '/home/momentino/PycharmProjects/llm-authority-bias/data/question_bank/neuro/question_bank.csv' --model "claude-3-haiku-20240307" --profession "general neurologist" --gender "female" --position "student"

#python ../cli.py measure --qbank '/home/momentino/PycharmProjects/llm-authority-bias/data/question_bank/neuro/question_bank.csv' --model "claude-3-haiku-20240307" --profession "general neurologist" --gender "male" --position "resident"
#python ../cli.py measure --qbank '/home/momentino/PycharmProjects/llm-authority-bias/data/question_bank/neuro/question_bank.csv' --model "claude-3-haiku-20240307" --profession "general neurologist" --gender "female" --position "resident"

#python ../cli.py measure --qbank '/home/momentino/PycharmProjects/llm-authority-bias/data/question_bank/neuro/question_bank.csv' --model "claude-3-haiku-20240307" --profession "general neurologist" --gender "male" --workplace_study "world-class institution"
#python ../cli.py measure --qbank '/home/momentino/PycharmProjects/llm-authority-bias/data/question_bank/neuro/question_bank.csv' --model "claude-3-haiku-20240307" --profession "general neurologist" --gender "female" --workplace_study "world-class institution"

#python ../cli.py measure --qbank '/home/momentino/PycharmProjects/llm-authority-bias/data/question_bank/neuro/question_bank.csv' --model "claude-3-haiku-20240307" --profession "general neurologist" --gender "male" --workplace_study "regional-level institution"
#python ../cli.py measure --qbank '/home/momentino/PycharmProjects/llm-authority-bias/data/question_bank/neuro/question_bank.csv' --model "claude-3-haiku-20240307" --profession "general neurologist" --gender "female" --workplace_study "regional-level institution"

#python ../cli.py measure --qbank '/home/momentino/PycharmProjects/llm-authority-bias/data/question_bank/neuro/question_bank.csv' --model "claude-3-haiku-20240307" --profession "general neurologist" --position "attending"
#python ../cli.py measure --qbank '/home/momentino/PycharmProjects/llm-authority-bias/data/question_bank/neuro/question_bank.csv' --model "claude-3-haiku-20240307" --profession "general neurologist" --position "resident"
#python ../cli.py measure --qbank '/home/momentino/PycharmProjects/llm-authority-bias/data/question_bank/neuro/question_bank.csv' --model "claude-3-haiku-20240307" --profession "general neurologist" --position "student"

#python ../cli.py measure --qbank '/home/momentino/PycharmProjects/llm-authority-bias/data/question_bank/neuro/question_bank.csv' --model "claude-3-haiku-20240307" --profession "general neurologist" --position "attending" --workplace_study "world-class institution"
#python ../cli.py measure --qbank '/home/momentino/PycharmProjects/llm-authority-bias/data/question_bank/neuro/question_bank.csv' --model "claude-3-haiku-20240307" --profession "general neurologist" --position "attending" --workplace_study "regional-level institution"
#python ../cli.py measure --qbank '/home/momentino/PycharmProjects/llm-authority-bias/data/question_bank/neuro/question_bank.csv' --model "claude-3-haiku-20240307" --profession "general neurologist" --position "resident" --workplace_study "world-class institution"
#python ../cli.py measure --qbank '/home/momentino/PycharmProjects/llm-authority-bias/data/question_bank/neuro/question_bank.csv' --model "claude-3-haiku-20240307" --profession "general neurologist" --position "resident" --workplace_study "regional-level institution"
#python ../cli.py measure --qbank '/home/momentino/PycharmProjects/llm-authority-bias/data/question_bank/neuro/question_bank.csv' --model "claude-3-haiku-20240307" --profession "general neurologist" --position "student" --workplace_study "world-class institution"
#python ../cli.py measure --qbank '/home/momentino/PycharmProjects/llm-authority-bias/data/question_bank/neuro/question_bank.csv' --model "claude-3-haiku-20240307" --profession "general neurologist" --position "student" --workplace_study "regional-level institution"

python ../cli.py measure --qbank '/home/momentino/PycharmProjects/llm-authority-bias/data/question_bank/neuro/question_bank.csv' --model "claude-3-haiku-20240307" --profession "general neurologist" --workplace_study "world-class institution"
#python ../cli.py measure --qbank '/home/momentino/PycharmProjects/llm-authority-bias/data/question_bank/neuro/question_bank.csv' --model "claude-3-haiku-20240307" --profession "general neurologist" --workplace_study "regional-level institution"

#python ../cli.py measure --qbank '/home/momentino/PycharmProjects/llm-authority-bias/data/question_bank/neuro/question_bank.csv' --model "claude-3-haiku-20240307" --profession "general neurologist" --gender "male" --position "attending" --workplace_study "world-class institution"
#python ../cli.py measure --qbank '/home/momentino/PycharmProjects/llm-authority-bias/data/question_bank/neuro/question_bank.csv' --model "claude-3-haiku-20240307" --profession "general neurologist" --gender "female" --position "attending" --workplace_study "world-class institution"
#python ../cli.py measure --qbank '/home/momentino/PycharmProjects/llm-authority-bias/data/question_bank/neuro/question_bank.csv' --model "claude-3-haiku-20240307" --profession "general neurologist" --gender "male" --position "attending" --workplace_study "regional-level institution"
#python ../cli.py measure --qbank '/home/momentino/PycharmProjects/llm-authority-bias/data/question_bank/neuro/question_bank.csv' --model "claude-3-haiku-20240307" --profession "general neurologist" --gender "female" --position "attending" --workplace_study "regional-level institution"
#python ../cli.py measure --qbank '/home/momentino/PycharmProjects/llm-authority-bias/data/question_bank/neuro/question_bank.csv' --model "claude-3-haiku-20240307" --profession "general neurologist" --gender "male" --position "resident" --workplace_study "world-class institution"
#python ../cli.py measure --qbank '/home/momentino/PycharmProjects/llm-authority-bias/data/question_bank/neuro/question_bank.csv' --model "claude-3-haiku-20240307" --profession "general neurologist" --gender "female" --position "resident" --workplace_study "world-class institution"
#python ../cli.py measure --qbank '/home/momentino/PycharmProjects/llm-authority-bias/data/question_bank/neuro/question_bank.csv' --model "claude-3-haiku-20240307" --profession "general neurologist" --gender "male" --position "resident" --workplace_study "regional-level institution"
#python ../cli.py measure --qbank '/home/momentino/PycharmProjects/llm-authority-bias/data/question_bank/neuro/question_bank.csv' --model "claude-3-haiku-20240307" --profession "general neurologist" --gender "female" --position "resident" --workplace_study "regional-level institution"
#python ../cli.py measure --qbank '/home/momentino/PycharmProjects/llm-authority-bias/data/question_bank/neuro/question_bank.csv' --model "claude-3-haiku-20240307" --profession "general neurologist" --gender "male" --position "student" --workplace_study "world-class institution"
#python ../cli.py measure --qbank '/home/momentino/PycharmProjects/llm-authority-bias/data/question_bank/neuro/question_bank.csv' --model "claude-3-haiku-20240307" --profession "general neurologist" --gender "female" --position "student" --workplace_study "world-class institution"
#python ../cli.py measure --qbank '/home/momentino/PycharmProjects/llm-authority-bias/data/question_bank/neuro/question_bank.csv' --model "claude-3-haiku-20240307" --profession "general neurologist" --gender "male" --position "student" --workplace_study "regional-level institution"
#python ../cli.py measure --qbank '/home/momentino/PycharmProjects/llm-authority-bias/data/question_bank/neuro/question_bank.csv' --model "claude-3-haiku-20240307" --profession "general neurologist" --gender "female" --position "student" --workplace_study "regional-level institution"